services:
  postgre-sekou-db:
    container_name: postgre-sekou-db
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: sidof
      POSTGRES_PASSWORD: sidof1/@
      PGDATA: /data/postgres
    volumes:
      - network-sekou:/data/postgres
    ports:
      - 5433:5432
    expose:
      - 5432
    networks:
      - network-sekou

#  house-rent-api:
#    container_name: sekou-api
#    image: sekou-api:v1
#    ports:
#      - 80:8084
#    depends_on:
#      - postgre-sekou-db
#    environment:
#      SPRING_APPLICATION_JSON: '{
#            "spring.datasource.url"  : "jdbc:postgresql://postgre-sekou-db:5432/dbsekou",
#            "spring.datasource.username" : "sidof",
#            "spring.datasource.password" : "sidof1/@",
#            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
#            "spring.jpa.hibernate.ddl-auto" : "update",
#            "spring.profiles.active" : "prod"
#          }'
#    networks:
#      - network-sekou


networks:
  network-sekou:
    driver: bridge
volumes:
  network-sekou: